name: Notify Team on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Teams notification
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"text\": \"New release: ${{ github.repository }} @ ${{ github.ref }}\"}" \
               ${{ secrets.TEAMS_WEBHOOK_URL }}