name: Notify on Release (call central workflow)

on:
  release:
    types: [published]

jobs:
  call-notify:
    if: ${{ !(contains(github.ref, 'demo') || contains(github.ref, 'staging') || contains(github.event.release.name, 'example') || contains(github.repository, 'example')) }}
    uses: K-test-inc/org-actions/.github/workflows/notify.yml@main
    with:
      message: "New release in ${{ github.repository }}: ${{ github.event.release.name }}"
      enabled: true

#############example with filter####
# name: Notify on Release (call central workflow)

# on:
#   release:
#     types: [published]

# jobs:
#   call-notify:
#     if: ${{ !(contains(github.ref, 'demo') || contains(github.ref, 'staging') || contains(github.event.release.name, 'example') || contains(github.repository, 'example')) }}
#     uses: K-test-inc/org-actions/.github/workflows/notify.yml@main
#     with:
#       message: "New release in ${{ github.repository }}: ${{ github.ref }}"
#       enabled: true
#     secrets:
#       TEAMS_WEBHOOKS_JSON: ${{ secrets.TEAMS_WEBHOOKS_JSON }}

######################################

#name: Notify Team on Release Github Actions
#
#on:
#  release:
#    types: [published]
#
#jobs:
#  notify:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Send Teams notification
#        run: |
#          curl -H "Content-Type: application/json" \
#               -d "{\"text\": \"New release: ${{ github.repository }} @ ${{ github.ref }}\"}" \
#               ${{ secrets.TEAMS_WEBHOOK_URL }}
